### ISSUE TITLE
Создать поискан репетиторов и поискан сотрудников App.

### ISSUE THREAD

**Issue by tsthien** [anewday1999/social_network_PO#6]
#### Включая:
1. Базу данных.
2. Пользовательский интерфейс (шаблон).
3. Обработку взаимодействия пользователя с базой данных.
#### Информация сообщения поискан репетиторов включается:
1. Заглавие
2. Описывание
3. Предмета
4. Календарь
5. Зарплат
6. Контакт
7. Срок действия сообщения
8. Автор.
#### Информация сообщения поискан сотрудников включается:
1. Заглавие
2. Описывание
3. Календарь
4. Зарплат
5. Контакт
6. Срок действия сообщения
7. Автор.

**Comment by Naleesh** [comment]
Создал поиск репетиторов!
Пока еще работаю над поискан сотрудников

**Comment by Naleesh** [comment]
Создал поиск  сотрудников
